### ISSUE TITLE
Execute commands - (k accept, k disband, k leave, k kick, )

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#42]
Please add this option, I need it to assign permissions on the server

example already in the plugin
# When a kingdom or a nation is created.
creation:
  kingdoms:
    # Show the pacifist/aggressor GUI?
    show-kingdom-type-gui: true

    # The default shield duration for new kingdoms to get prepared.
    newbie-protection: 5 days

    # Commands executed when the kingdom is created. You can use all the placeholders.
    commands: [ "ExternalPermissionPlugin %player% permission" ]
  nations:
    # The default shield duration for new kingdoms to get prepared.
    newbie-protection: 0

    # Commands executed when the nation is created. You can use all the placeholders.
    commands: [ ]

**Comment by CryptoMorin** [comment]
Hi you can do this, but in in the 1.15 beta version. You can use [events](https://github.com/CryptoMorin/KingdomsX/blob/af6dffda01951065cd085b07701594e690e3e95a/core/src/main/resources/config.yml#L958-L979) option.

```yml
events:
  org.kingdoms.events.general.KingdomCreateEvent:
    commands: []
  org.kingdoms.events.general.nation.NationCreateEvent:
    commands: [ ]
```
